In [37]:
# import TfidfVectorizer from sklearn
from sklearn.feature_extraction.text import TfidfVectorizer

# Pandas for displaying the TF-IDF matrix
import pandas as pd
print("Libraries Imported Successfully!")

Libraries Imported Successfully!

In [38]:
# Step 1: Create the Corpus

corpus = ["The quick brown fox jumps over the lazy dog.",
    "The dog was not lazy, the dog was just tired.",
    "A quick fox can jump higher than a lazy dog.",
    "The brown fox and the blue bird are friends.",
    "Can a dog jump over a fox? Yes, a dog can.",
    "The tired bird rests on the brown branch.",
    "Lazy dogs sleep all day, but quick foxes run.",
         ]
print("Corpus:\n", corpus)

Corpus:
 ['The quick brown fox jumps over the lazy dog.', 'The dog was not lazy, the dog was just tired.', 'A quick fox can jump higher than a lazy dog.', 'The brown fox and the blue bird are friends.', 'Can a dog jump over a fox? Yes, a dog can.', 'The tired bird rests on the brown branch.', 'Lazy dogs sleep all day, but quick foxes run.']

In [39]:
for i, sentence in enumerate(corpus):
    print(f"Document: {i+1}: {sentence}")

Document: 1: The quick brown fox jumps over the lazy dog.
Document: 2: The dog was not lazy, the dog was just tired.
Document: 3: A quick fox can jump higher than a lazy dog.
Document: 4: The brown fox and the blue bird are friends.
Document: 5: Can a dog jump over a fox? Yes, a dog can.
Document: 6: The tired bird rests on the brown branch.
Document: 7: Lazy dogs sleep all day, but quick foxes run.

In [40]:
# Step 2: Total Number of Documents
total_documents = len(corpus)

print("Total Documents =", total_documents)

Total Documents = 7

In [41]:
# Step 3: Create a TF-IDF object
tfidf = TfidfVectorizer()
print(tfidf)

TfidfVectorizer()

In [42]:
# Step 4: Learn Vocabulary

# Learn vocabulary and calculate TF-IDF values
tfidf_matrix = tfidf.fit_transform(corpus)
print("TF IDF learned Successfully!")

TF IDF learned Successfully!

In [43]:
# Step 5: Display Vocabulary

vocabulary = tfidf.get_feature_names_out()
print("Vocabulary:\n")

for word in vocabulary:
    print(word)

Vocabulary:

all
and
are
bird
blue
branch
brown
but
can
day
dog
dogs
fox
foxes
friends
higher
jump
jumps
just
lazy
not
on
over
quick
rests
run
sleep
than
the
tired
was
yes

In [44]:
print("Shape of TF-IDF Matrix")
print(tfidf_matrix.shape)

Shape of TF-IDF Matrix
(7, 32)

In [45]:
dense_matrix = tfidf_matrix.toarray()
print(dense_matrix)

[[0.         0.         0.         0.         0.         0.
  0.30669154 0.         0.         0.         0.266272   0.
  0.266272   0.         0.         0.         0.         0.43224612
  0.         0.266272   0.         0.         0.3588014  0.30669154
  0.         0.         0.         0.         0.532544   0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.38758766 0.
  0.         0.         0.         0.         0.         0.
  0.31459047 0.19379383 0.31459047 0.         0.         0.
  0.         0.         0.         0.         0.38758766 0.2611371
  0.62918093 0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.37048703 0.         0.27494408 0.
  0.27494408 0.         0.         0.44632373 0.37048703 0.
  0.         0.27494408 0.         0.         0.         0.31668003
  0.         0.         0.         0.44632373 0.         0.
  0.         0.        ]
 [0.         0.3755612  0.3755612  0.31174805 0.3755612  0.
  0.2664719  0.         0.         0.         0.         0.
  0.23135299 0.         0.3755612  0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.46270597 0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.62607195 0.         0.46461755 0.
  0.23230878 0.         0.         0.         0.31303598 0.
  0.         0.         0.         0.         0.31303598 0.
  0.         0.         0.         0.         0.         0.
  0.         0.37711276]
 [0.         0.         0.         0.32813468 0.         0.39530208
  0.28047864 0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.39530208 0.         0.
  0.39530208 0.         0.         0.         0.48702751 0.32813468
  0.         0.        ]
 [0.35616943 0.         0.         0.         0.         0.
  0.         0.35616943 0.         0.35616943 0.         0.35616943
  0.         0.35616943 0.         0.         0.         0.
  0.         0.21940728 0.         0.         0.         0.25271286
  0.         0.35616943 0.35616943 0.         0.         0.
  0.         0.        ]]

In [46]:
# Displaqy TF-IDF Matix as Dataframe
df1=pd.DataFrame(dense_matrix,columns=vocabulary)

In [47]:
df = pd.DataFrame(
    dense_matrix,
    columns=vocabulary)

df.index = [
    "Document 1",
    "Document 2",
    "Document 3",
    "Document 4",
    "Document 5",
    "Document 6",
    "Document 7",
]

print(df)
df

                 all       and       are      bird      blue    branch  \
Document 1  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
Document 2  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
Document 3  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
Document 4  0.000000  0.375561  0.375561  0.311748  0.375561  0.000000
Document 5  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
Document 6  0.000000  0.000000  0.000000  0.328135  0.000000  0.395302
Document 7  0.356169  0.000000  0.000000  0.000000  0.000000  0.000000

               brown       but       can       day  ...      over     quick  \
Document 1  0.306692  0.000000  0.000000  0.000000  ...  0.358801  0.306692
Document 2  0.000000  0.000000  0.000000  0.000000  ...  0.000000  0.000000
Document 3  0.000000  0.000000  0.370487  0.000000  ...  0.000000  0.316680
Document 4  0.266472  0.000000  0.000000  0.000000  ...  0.000000  0.000000
Document 5  0.000000  0.000000  0.626072  0.000000  ...  0.313036  0.000000
Document 6  0.280479  0.000000  0.000000  0.000000  ...  0.000000  0.000000
Document 7  0.000000  0.356169  0.000000  0.356169  ...  0.000000  0.252713

               rests       run     sleep      than       the     tired  \
Document 1  0.000000  0.000000  0.000000  0.000000  0.532544  0.000000
Document 2  0.000000  0.000000  0.000000  0.000000  0.387588  0.261137
Document 3  0.000000  0.000000  0.000000  0.446324  0.000000  0.000000
Document 4  0.000000  0.000000  0.000000  0.000000  0.462706  0.000000
Document 5  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
Document 6  0.395302  0.000000  0.000000  0.000000  0.487028  0.328135
Document 7  0.000000  0.356169  0.356169  0.000000  0.000000  0.000000

                 was       yes
Document 1  0.000000  0.000000
Document 2  0.629181  0.000000
Document 3  0.000000  0.000000
Document 4  0.000000  0.000000
Document 5  0.000000  0.377113
Document 6  0.000000  0.000000
Document 7  0.000000  0.000000

[7 rows x 32 columns]

,all,and,are,bird,blue,branch,brown,but,can,day,...,over,quick,rests,run,sleep,than,the,tired,was,yes
Document 1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.306692,0.000000,0.000000,0.000000,...,0.358801,0.306692,0.000000,0.000000,0.000000,0.000000,0.532544,0.000000,0.000000,0.000000
Document 2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.387588,0.261137,0.629181,0.000000
Document 3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.370487,0.000000,...,0.000000,0.316680,0.000000,0.000000,0.000000,0.446324,0.000000,0.000000,0.000000,0.000000
Document 4,0.000000,0.375561,0.375561,0.311748,0.375561,0.000000,0.266472,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.462706,0.000000,0.000000,0.000000
Document 5,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.626072,0.000000,...,0.313036,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.377113
Document 6,0.000000,0.000000,0.000000,0.328135,0.000000,0.395302,0.280479,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.395302,0.000000,0.000000,0.000000,0.487028,0.328135,0.000000,0.000000
Document 7,0.356169,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.356169,0.000000,0.356169,...,0.000000,0.252713,0.000000,0.356169,0.356169,0.000000,0.000000,0.000000,0.000000,0.000000

In [48]:
new_sentence = ["The dog was not lazy, the dog was just"]
new_vector = tfidf.transform(new_sentence)
print(new_vector.toarray())

[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.40151971 0.
  0.         0.         0.         0.         0.         0.
  0.32589859 0.20075985 0.32589859 0.         0.         0.
  0.         0.         0.         0.         0.40151971 0.
  0.65179717 0.        ]]

In [51]:
# Step 10:
new_df = pd.DataFrame(
    new_vector.toarray(),
    columns=vocabulary,
    index=["New Sentence"]
)

print(new_vector)
new_df

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 6 stored elements and shape (1, 32)>
  Coords	Values
  (0, 10)	0.4015197060194925
  (0, 18)	0.3258985866737141
  (0, 19)	0.20075985300974625
  (0, 20)	0.3258985866737141
  (0, 28)	0.4015197060194925
  (0, 30)	0.6517971733474281

,all,and,are,bird,blue,branch,brown,but,can,day,...,over,quick,rests,run,sleep,than,the,tired,was,yes
New Sentence,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.40152,0.0,0.651797,0.0